name: Generate Snake Animation

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"   # todos os dias
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub contribution snake (dark)
        uses: Platane/snk@v3
        with:
          github_user_name: p0k4

          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

          # Snake color
          color_snake: "#22c55e"

          # Contribution colors (GitHub dark mode palette)
          color_dots: |
            #161b22
            #0e4429
            #006d32
            #26a641
            #39d353

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
