name: Generate Snake Animation

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake (dark)
        uses: Platane/snk@v3
        with:
          github_user_name: p0k4
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
          args: |
            --background-color #0d1117
            --snake-color #a855f7
            --dot-color-0 #161b22
            --dot-color-1 #0e4429
            --dot-color-2 #006d32
            --dot-color-3 #26a641
            --dot-color-4 #39d353

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
